# frozen_string_literal: true

source "https://rails-assets.org"
source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "active_decorator"
gem "ancestry"
gem "aws-sdk-sqs"
gem "carrierwave"
gem "carrierwave-i18n"
gem "data_migrate"
gem "devise", "~> 4.5.0"
gem "dry-configurable"
gem "fog"
gem "gaffe"
gem "health-monitor-rails"
gem "jbuilder"
gem "kakurenbo-puti"
gem "mysql2", "~> 0.5.2"
gem "oj"
gem "paper_trail"
gem "puma"
gem "pundit"
gem "rails"
gem "redis-namespace", "~> 1.6"
gem "rmagick"
gem "sidekiq", "~> 5.1"
gem "slim-rails", "~> 3.1", ">= 3.1.3"
gem "trailblazer-rails"

group :development do
  gem "annotate"
  gem "better_errors"
  gem "binding_of_caller"
  gem "html2slim"
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "meta_request"
  gem "rails-erd", "1.5.0"
  gem "rubocop", require: false
  gem "rubocop-rspec"
end

group :development, :test do
  gem "awesome_print", require: "ap"
  gem "bullet"
  gem "guard"
  gem "guard-rspec"
  gem "guard-rubocop"
  gem "i18n-debug"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rspec-rails"
  gem "rspec_api_documentation"
end

group :test do
  gem "database_rewinder"
  gem "fuubar"
  gem "rspec_junit_formatter", "~> 0.4.1"
  gem "vcr"
  gem "webmock"
end
