const actionTypes = {
  ADD_OBJECTIVE: 'ADD_OBJECTIVE',
  ADDED_OBJECTIVE: 'ADDED_OBJECTIVE',
  FETCH_OBJECTIVES: 'FETCH_OBJECTIVES',
  FETCHED_OBJECTIVES: 'FETCHED_OBJECTIVES',
  UPDATE_OBJECTIVE: 'UPDATE_OBJECTIVE',
  UPDATED_OBJECTIVE: 'UPDATED_OBJECTIVE',
  REMOVE_OBJECTIVE: 'REMOVE_OBJECTIVE',
  REMOVED_OBJECTIVE: 'REMOVED_OBJECTIVE',
  FETCH_KEY_RESULTS: 'FETCH_KEY_RESULTS',
  FETCHED_KEY_RESULTS: 'FETCHED_KEY_RESULTS',
  ADD_KEY_RESULT: 'ADD_KEY_RESULT',
  ADDED_KEY_RESULT: 'ADDED_KEY_RESULT',
  OPEN_KEY_RESULT_FORM_MODAL: 'OPEN_KEY_RESULT_FORM_MODAL',
  CLOSE_KEY_RESULT_FORM_MODAL: 'CLOSE_KEY_RESULT_FORM_MODAL',
  OPEN_OBJECTIVE_FORM_MODAL: 'OPEN_OBJECTIVE_FORM_MODAL',
  CLOSE_OBJECTIVE_FORM_MODAL: 'CLOSE_OBJECTIVE_FORM_MODAL'
};
export default actionTypes;